FROM busybox:latest

ENTRYPOINT sh -c "cd /tmp/docker/hooks && ls | xargs chmod +x && cd /tmp/.git/hooks && find /tmp/.git/hooks/ -maxdepth 1 -type l -delete && find ../../docker/hooks -type f -exec ln -sf {} /tmp/.git/hooks/ \;"


